export const COMMANDS = {
  openChat: "alysis.openChat",
  newSession: "alysis.newSession",
  newWorktree: "alysis.newWorktree",
  moveToWorktree: "alysis.moveToWorktree",
  reviewGitChanges: "alysis.reviewGitChanges",
  openSourceControl: "alysis.openSourceControl",
  showHistory: "alysis.showHistory",
  showSettings: "alysis.showSettings",
  showModels: "alysis.showModels",
  showForge: "alysis.showForge",
  showBrowser: "alysis.showBrowser",
  runTask: "alysis.runTask",
  addSelection: "alysis.addSelection",
  forgePlan: "alysis.forgePlan",
  forgeListPlans: "alysis.forgeListPlans",
  forgeOpenPlan: "alysis.forgeOpenPlan",
  forgeExecute: "alysis.forgeExecute",
  runSwarm: "alysis.runSwarm",
  cancelCurrentRun: "alysis.cancelCurrentRun",
  runDoctor: "alysis.runDoctor",
  configureProvider: "alysis.configureProvider",
  pickModel: "alysis.pickModel",
  showBridgeHealth: "alysis.showBridgeHealth",
  sessionActions: "alysis.sessionActions",
  manageProfiles: "alysis.manageProfiles",
  manageToolsSkills: "alysis.manageToolsSkills",
  manageMcpHooks: "alysis.manageMcpHooks",
  manageExtensions: "alysis.manageExtensions",
  healthDiagnostics: "alysis.healthDiagnostics",
  manageForgeAssets: "alysis.manageForgeAssets",
  checkForUpdates: "alysis.checkForUpdates",
  manageInfo: "alysis.manage.info",
  manageTrust: "alysis.manage.trust",
  manageUntrust: "alysis.manage.untrust",
  manageEnable: "alysis.manage.enable",
  manageDisable: "alysis.manage.disable",
  manageRemove: "alysis.manage.remove",
  manageMcpLogin: "alysis.manage.mcpLogin",
  manageMcpLogout: "alysis.manage.mcpLogout",
  manageRefresh: "alysis.manage.refresh",
  copyCliInstallCommand: "alysis.copyCliInstallCommand",
  copyCliUpgradeCommand: "alysis.copyCliUpgradeCommand",
  openSetupGuide: "alysis.openSetupGuide",
  locateCli: "alysis.locateCli",
  sessionShow: "alysis.session.show",
  sessionScore: "alysis.session.score",
  sessionUsage: "alysis.session.usage",
  sessionResume: "alysis.session.resume",
  sessionCompact: "alysis.session.compact",
  sessionClear: "alysis.session.clear"
} as const;

export const GETTING_STARTED_WALKTHROUGH_ID = "alysis.gettingStarted";
export const GETTING_STARTED_WALKTHROUGH = "alysisai.vscode-alysis#alysis.gettingStarted";
