from __future__ import annotations

from typing import Any

from .. import __version__
from ..host_actions import (
    HOST_ACTION_MAX_ARGUMENT_BYTES,
    HOST_ACTION_MAX_RESULT_BYTES,
    HOST_ACTION_PROTOCOL_VERSION,
    HOST_ACTIONS,
)
from ..surface.events import EVENT_REGISTRY
from .activity_events import activity_capabilities
from .context_blocks import context_capabilities
from .management_protocol import MANAGEMENT_FEATURES
from .protocol import PROTOCOL_VERSION

DEFAULT_APPROVAL_TIMEOUT_SECONDS = 300

SUPPORTED_METHODS = (
    "initialize",
    "health",
    "getCapabilities",
    "bridge.shutdown",
    "session.create",
    "chat.send",
    "chat.queue.list",
    "chat.queue.get",
    "chat.queue.delete",
    "checkpoint.list",
    "checkpoint.diff",
    "checkpoint.revert",
    "checkpoint.redo",
    "checkpoint.branch",
    "session.tasks.get",
    "session.tasks.replace",
    "session.questions.create",
    "session.questions.get",
    "session.questions.list",
    "session.questions.answer",
    "session.questions.cancel",
    "run.start",
    "session.status",
    "session.usage",
    "session.history",
    "session.search",
    "session.context",
    "session.compact",
    "session.resume",
    "session.images.list",
    "session.images.add",
    "session.images.clear",
    "session.setMode",
    "session.setModel",
    "session.setStream",
    "session.setActiveWorkdir",
    "session.modelInfo",
    "session.personas.list",
    "session.persona.set",
    "session.subagents.status",
    "session.subagents.setEnabled",
    "session.trace.status",
    "session.trace.setLevel",
    "session.trace.listEvents",
    "session.trace.readArtifact",
    "session.trace.clear",
    "session.terminals.list",
    "session.terminals.show",
    "session.terminals.kill",
    "session.terminals.clear",
    "session.clear",
    "session.cancel",
    "approval.respond",
    "host.action.respond",
    "permission.rules.list",
    "permission.rules.grant",
    "permission.rules.revoke",
    "permission.evaluate",
    "permission.session.list",
    "permission.session.revoke",
    "code.review.start",
    "code.review.result",
    "job.status",
    "session.list",
    "session.getEvents",
    "artifact.list",
    "artifact.read",
    "browser.start",
    "browser.navigate",
    "browser.snapshot",
    "browser.screenshot",
    "browser.artifact.read",
    "browser.diagnostics",
    "browser.click",
    "browser.type",
    "browser.status",
    "browser.list",
    "browser.close",
    "forge.plan",
    "forge.plan.start",
    "forge.plan.result",
    "forge.list",
    "forge.open",
    "forge.resume",
    "forge.status",
    "forge.attach",
    "forge.show",
    "forge.plan.getState",
    "forge.plan.setAssistant",
    "forge.plan.setGoal",
    "forge.plan.updateTask",
    "forge.plan.validate",
    "forge.plan.regenerate",
    "forge.plan.regenerate.start",
    "forge.plan.regenerate.result",
    "forge.review",
    "forge.review.start",
    "forge.review.result",
    "forge.assets.list",
    "forge.assets.show",
    "forge.assets.add",
    "forge.assets.delete",
    "forge.assets.edit",
    "forge.assets.refresh",
    "forge.assets.cancelPending",
    "forge.assets.checkPlan",
    "forge.assets.pruneLegacy",
    "forge.executePreview",
    "forge.execute",
    "forge.cancel",
    "forge.swarm.start",
    "forge.swarm.resume",
    "forge.swarm.list",
    "forge.swarm.status",
    "forge.swarm.result",
    "forge.swarm.cancel",
    "forge.swarm.reconcile",
    "forge.swarm.review",
    "forge.swarm.apply",
    "forge.swarm.discard",
    "diff.list",
    "diff.get",
    "config.get",
    "config.set",
    "config.schema",
    "config.validate",
    "profile.list",
    "profile.show",
    "profile.add",
    "profile.remove",
    "profile.use",
    "profile.rename",
    "profile.presets",
    "profile.preset",
    "profile.convert",
    "session.show",
    "session.score",
    "tools.catalog",
    "tool.list",
    "tool.info",
    "tool.trust",
    "tool.untrust",
    "skill.list",
    "skill.info",
    "skill.init",
    "skill.validate",
    "skill.install",
    "skill.enable",
    "skill.disable",
    "skill.remove",
    "doctor.summary",
    "doctor.providers",
    "doctor.providers.live",
    "doctor.bundle",
    "sandbox.doctor",
    "sandbox.setup",
    "sandbox.pull",
    "update.check",
    "report.create",
    "mcp.status",
    "mcp.server.status",
    "mcp.server.enable",
    "mcp.server.disable",
    "mcp.server.restart",
    "mcp.prompts.list",
    "mcp.prompts.get",
    "mcp.auth.status",
    "mcp.auth.login.start",
    "mcp.auth.login.status",
    "mcp.auth.login.cancel",
    "mcp.auth.logout",
    "hooks.list",
    "hooks.doctor",
    "hooks.trace",
    "hooks.test",
    "hooks.trust",
    "hooks.untrust",
    "hooks.init",
    "hooks.effective",
    "hooks.enable",
    "hooks.disable",
    "conventions.list",
    "conventions.render",
    "ext.search",
    "ext.list",
    "ext.info",
    "ext.install",
    "ext.uninstall",
    "ext.enable",
    "ext.disable",
)

SUPPORTED_MODES = ("readonly", "review", "auto")


def capabilities_payload() -> dict[str, Any]:
    return {
        "protocol_version": PROTOCOL_VERSION,
        "methods": list(SUPPORTED_METHODS),
        "events": sorted(EVENT_REGISTRY),
        "modes": list(SUPPORTED_MODES),
        "transport": "stdio-jsonl",
        "features": {
            "structured_surface_events": True,
            "graceful_shutdown": {
                "supported": True,
                "method": "bridge.shutdown",
                "closes_sessions": True,
                "terminates_background_processes": True,
            },
            "semantic_activity": activity_capabilities(),
            "typed_ide_context": context_capabilities(),
            "host_actions": {
                "supported": True,
                "protocol_version": HOST_ACTION_PROTOCOL_VERSION,
                "session_negotiated": True,
                "workspace_trust_required": True,
                "workspace_fenced": True,
                "capability_fenced": True,
                "request_event": "host_action_requested",
                "cancellation_event": "host_action_cancelled",
                "session_closed_event": "session_closed",
                "response_method": "host.action.respond",
                "actions": list(HOST_ACTIONS),
                "max_argument_bytes": HOST_ACTION_MAX_ARGUMENT_BYTES,
                "max_result_bytes": HOST_ACTION_MAX_RESULT_BYTES,
                "late_responses_rejected": True,
                "duplicate_responses_rejected": True,
            },
            "prompt_queue": {
                "supported": True,
                "durable": True,
                "ordered_per_session": True,
                "idempotency_keys": True,
                "initial_run_workspace_scoped_idempotency": True,
                "initial_run_payload_conflict_detection": True,
                "initial_run_orphan_reconciliation": True,
                "delete_pending": True,
                "fenced_leases": True,
                "restart_recovery": True,
                "methods": [
                    "chat.queue.list",
                    "chat.queue.get",
                    "chat.queue.delete",
                ],
            },
            "checkpoints": {
                "supported": True,
                "external_storage": True,
                "project_git_untouched": True,
                "sensitive_files_excluded": True,
                "optimistic_revert": True,
                "redo": True,
                "methods": [
                    "checkpoint.list",
                    "checkpoint.diff",
                    "checkpoint.revert",
                    "checkpoint.redo",
                    "checkpoint.branch",
                ],
            },
            "permission_policy": {
                "supported": True,
                "effects": ["allow", "ask", "deny"],
                "ordered_rules": True,
                "explainable_decisions": True,
                "persistent_rules": True,
                "session_exact_grants": True,
                "list_and_revoke": True,
                "sensitive_override_bypassable": False,
                "external_directory_override_bypassable": False,
                "command_patterns_redacted": True,
                "methods": [
                    "permission.rules.list",
                    "permission.rules.grant",
                    "permission.rules.revoke",
                    "permission.evaluate",
                    "permission.session.list",
                    "permission.session.revoke",
                ],
            },
            "session_search": {
                "supported": True,
                "workspace_scoped": True,
                "owner_scoped": True,
                "bounded": True,
                "redacted": True,
                "attachable_context_type": "past_session",
                "methods": ["session.search"],
            },
            "structured_state": {
                "supported": True,
                "durable": True,
                "external_storage": True,
                "workspace_and_session_scoped": True,
                "task_revision_cas": True,
                "one_active_task": True,
                "question_idempotency": True,
                "question_resolution_fenced": True,
                "restart_recovery": True,
                "methods": [
                    "session.tasks.get",
                    "session.tasks.replace",
                    "session.questions.create",
                    "session.questions.get",
                    "session.questions.list",
                    "session.questions.answer",
                    "session.questions.cancel",
                ],
            },
            "resumable_swarm": {
                "supported": True,
                "durable": True,
                "external_storage": True,
                "workspace_and_session_scoped": True,
                "idempotent_start": True,
                "explicit_resume": True,
                "fresh_permission_fingerprint_required": True,
                "fenced_worker_leases": True,
                "restart_recovery": True,
                "atomic_cancellation": True,
                "exactly_once_usage_events": True,
                "methods": [
                    "forge.swarm.start",
                    "forge.swarm.resume",
                    "forge.swarm.list",
                    "forge.swarm.status",
                    "forge.swarm.result",
                    "forge.swarm.cancel",
                ],
            },
            "managed_browser": {
                "supported": True,
                "owned_chromium_processes": True,
                "loopback_cdp_only": True,
                "private_profiles_outside_workspaces": True,
                "guarded_navigation": True,
                "redirect_and_subresource_interception": True,
                "persistent_child_target_interception": True,
                "validating_egress_proxy": True,
                "dns_resolution_pinned_to_numeric_connect": True,
                "no_direct_network_fallback": True,
                "loopback_proxy_bypass_removed": True,
                "non_proxied_udp_disabled": True,
                "public_destinations_by_default": True,
                "local_destinations_require_confirmation": True,
                "direct_loopback_scope": True,
                "direct_loopback_scope_agent_isolated": True,
                "direct_loopback_scope_denies_lan_and_link_local": True,
                "bounded_snapshots": True,
                "chunked_screenshot_artifacts": True,
                "bounded_diagnostics": True,
                "session_cleanup": True,
                "methods": [
                    "browser.start",
                    "browser.navigate",
                    "browser.snapshot",
                    "browser.screenshot",
                    "browser.artifact.read",
                    "browser.diagnostics",
                    "browser.click",
                    "browser.type",
                    "browser.status",
                    "browser.list",
                    "browser.close",
                ],
            },
            "live_mcp_lifecycle": {
                "supported": True,
                "session_owned_manager": True,
                "workspace_bound": True,
                "server_bound": True,
                "single_client_lease_per_server": True,
                "status_materializes_connection": False,
                "status_checks_stdio_process_liveness": True,
                "mutations_require_workspace_trust": True,
                "mutations_require_idle_session": True,
                "disable_fail_closed": True,
                "reconnect_catalog_fenced": True,
                "reconnect_atomic": True,
                "server_diagnostics_in_protocol": False,
                "session_cleanup": True,
                "methods": [
                    "mcp.server.status",
                    "mcp.server.enable",
                    "mcp.server.disable",
                    "mcp.server.restart",
                ],
            },
            "code_review": {
                "supported": True,
                "asynchronous": True,
                "scopes": ["working_tree", "branch", "commit", "range"],
                "structured_findings": True,
                "bounded": True,
                "sensitive_files_excluded": True,
                "methods": ["code.review.start", "code.review.result"],
            },
            "terminal_output_scraping": False,
            "workspace_fail_closed": True,
            "secret_redaction": True,
            "artifacts": True,
            "run_chat_options": {
                "temperature": True,
                "stream": True,
                "verify_commands": True,
                "image_paths": True,
                "image_binary_jsonl": False,
                "model_override": True,
                "base_url_override": True,
                "max_steps": True,
                "no_log": True,
                "yes": True,
                "subagents_enabled_config_default": True,
                "active_workdir": True,
                "terminal_output_scraping": False,
                "session_methods": [
                    "session.status",
                    "session.usage",
                    "session.history",
                    "session.context",
                    "session.compact",
                    "session.resume",
                    "session.images.list",
                    "session.images.add",
                    "session.images.clear",
                    "session.setMode",
                    "session.setModel",
                    "session.setStream",
                    "session.setActiveWorkdir",
                    "session.modelInfo",
                    "session.subagents.status",
                    "session.subagents.setEnabled",
                    "session.trace.status",
                    "session.trace.setLevel",
                    "session.trace.listEvents",
                    "session.trace.readArtifact",
                    "session.trace.clear",
                    "session.terminals.list",
                    "session.terminals.show",
                    "session.terminals.kill",
                    "session.terminals.clear",
                    "session.clear",
                ],
                "session_method_capabilities": {
                    "session.modelInfo": {
                        "supported": True,
                        "provider_metadata": True,
                        "redacted_base_url": True,
                        "secret_values_included": False,
                        "source_values": [
                            "provider_reported",
                            "config",
                            "registry",
                            "unknown",
                        ],
                    },
                    "session.subagents": {
                        "supported": True,
                        "status_method": "session.subagents.status",
                        "set_enabled_method": "session.subagents.setEnabled",
                        "status_toggle_only": True,
                        "explicit_execution_supported": False,
                        "trust_required_for_toggle": True,
                        "lifecycle_event": "subagent_state_changed",
                        "execution_lifecycle": "in_turn_parent_owned",
                        "cancellation": "parent_job",
                        "independently_resumable": False,
                        "approvals": "host_managed_parent_session",
                        "background_worker_surface": "forge.swarm",
                        "forge_execute_subagents_supported": False,
                    },
                    "session.trace": {
                        "supported": True,
                        "methods": [
                            "session.trace.status",
                            "session.trace.setLevel",
                            "session.trace.listEvents",
                            "session.trace.readArtifact",
                            "session.trace.clear",
                        ],
                        "levels": ["off", "compact", "full"],
                        "full_trace_requires_confirmation": True,
                        "clear_mutates": True,
                        "clear_trust_required": False,
                        "replay_preserved_after_clear": True,
                        "redacted": True,
                        "secret_values_included": False,
                        "bounded": True,
                        "raw_provider_headers_included": False,
                        "environment_variables_included": False,
                        "source": "structured_protocol_events_and_scoped_artifacts",
                    },
                    "session.terminals": {
                        "supported": True,
                        "methods": [
                            "session.terminals.list",
                            "session.terminals.show",
                            "session.terminals.kill",
                            "session.terminals.clear",
                        ],
                        "manager_required": True,
                        "unavailable_result_when_no_manager": True,
                        "arbitrary_shell_execution": False,
                        "interactive_pty_streaming": False,
                        "redacted": True,
                        "secret_values_included": False,
                        "bounded_output": True,
                        "kill_trust_required": True,
                        "clear_trust_required": True,
                        "mutation_confirmation_required": True,
                    },
                    "session.history": {
                        "supported": True,
                        "redacted": True,
                        "secret_values_included": False,
                        "bounded_results": True,
                        "default_max_results": 50,
                        "max_results_upper_bound": 500,
                        "default_max_text_chars": 500,
                        "max_text_chars_upper_bound": 4000,
                    },
                    "session.context": {
                        "supported": True,
                        "token_accounting": "tokenizer_estimate",
                        "token_accounting_approximate": True,
                        "message_count_supported": True,
                        "source": "live_session_tokenizer_estimate",
                        "source_values": [
                            "provider_reported",
                            "tokenizer_estimate",
                            "approximate",
                            "unavailable",
                        ],
                    },
                    "session.compact": {
                        "supported": True,
                        "real_compaction_supported": True,
                        "mutates_context": True,
                        "token_accounting": "tokenizer_estimate",
                        "token_accounting_approximate": True,
                        "behavior": "uses_live_cli_conversation_compactor_when_enabled_for_session",
                    },
                    "session.resume": {
                        "supported": True,
                        "model_context_replay_supported": True,
                        "retained_history_metadata_supported": True,
                        "bounded_replay": True,
                        "redacts_replayed_messages": True,
                        "behavior": "bounded_retained_session_log_replay_into_live_session",
                    },
                    "session.images": {
                        "supported": True,
                        "methods": [
                            "session.images.list",
                            "session.images.add",
                            "session.images.clear",
                        ],
                        "workspace_scoped_paths": True,
                        "rejects_symlinks": True,
                        "binary_jsonl": False,
                        "paste_image": {
                            "supported": True,
                            "clipboard_binary_jsonl": False,
                            "vscode_file_picker_fallback": True,
                            "stores_workspace_scoped_paths": True,
                        },
                        "clears_after_successful_turn": True,
                        "retained_on_failed_turn": True,
                    },
                },
            },
            "forge": {
                "plan": {
                    "supported": True,
                    "schema": "ide_forge_plan_v1",
                    "async": True,
                    "start_method": "forge.plan.start",
                    "result_method": "forge.plan.result",
                    "compat_method": "forge.plan",
                    "durable_acceptance": True,
                    "external_private_storage": True,
                    "idempotency_key_supported": True,
                    "idempotency_key_and_payload_hashed": True,
                    "payload_conflict_detection": True,
                    "acknowledgement_after_durable_acceptance": True,
                    "stable_job_id_across_bridge_restart": True,
                    "job_status_restart_recovery": True,
                    "result_restart_recovery": True,
                    "fenced_worker_leases": True,
                    "worker_heartbeat": True,
                    "expired_running_lease": "indeterminate_no_automatic_reexecution",
                    "legacy_sync_exactly_once": False,
                    "terminal_output_scraping": False,
                    "planner": "forge_planner",
                    "shallow_fallback": False,
                },
                "list": {"supported": True, "durable": True},
                "open": {"supported": True, "durable": True},
                "resume": {"supported": True, "alias": "forge.open"},
                "status": {"supported": True},
                "attach": {
                    "supported": True,
                    "method": "forge.attach",
                    "mutates": True,
                    "trust_required": True,
                    "path_scoped": True,
                    "terminal_output_scraping": False,
                },
                "show": {
                    "supported": True,
                    "method": "forge.show",
                    "mutates": False,
                    "trust_required": False,
                },
                "plan_editing": {
                    "supported": True,
                    "methods": {
                        "forge.plan.getState": {
                            "supported": True,
                            "mutates": False,
                            "trust_required": False,
                        },
                        "forge.plan.setAssistant": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                            "optimistic_revision": True,
                        },
                        "forge.plan.setGoal": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                            "optimistic_revision": True,
                        },
                        "forge.plan.updateTask": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                            "optimistic_revision": True,
                            "mutable_fields": ["title", "body", "status"],
                        },
                        "forge.plan.validate": {
                            "supported": True,
                            "mutates": False,
                            "trust_required": False,
                        },
                        "forge.plan.regenerate": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                            "optimistic_revision": True,
                            "terminal_output_scraping": False,
                            "unsafe_execution_exposed": False,
                            "async": True,
                            "start_method": "forge.plan.regenerate.start",
                            "result_method": "forge.plan.regenerate.result",
                            "compat_method": "forge.plan.regenerate",
                            "cancellation": "cooperative_checkpoint_cancellation",
                            "conflict_detection": "optimistic_revision_commit_check",
                            "lock_free_planner": True,
                        },
                    },
                    "terminal_output_scraping": False,
                    "unsafe_execution_exposed": False,
                },
                "review": {
                    "supported": True,
                    "method": "forge.review",
                    "mutates": True,
                    "trust_required": True,
                    "inline_secrets_in_params": False,
                    "terminal_prompts": False,
                    "async": True,
                    "start_method": "forge.review.start",
                    "result_method": "forge.review.result",
                    "compat_method": "forge.review",
                    "cancellation": "cooperative_checkpoint_cancellation",
                    "cancellation_granularity": "before_and_after_provider_call",
                },
                "assets": {
                    "supported": True,
                    "path_scoped": True,
                    "rejects_symlinks": True,
                    "max_source_bytes": 26214400,
                    "methods": {
                        "forge.assets.list": {
                            "supported": True,
                            "mutates": False,
                            "trust_required": False,
                        },
                        "forge.assets.show": {
                            "supported": True,
                            "mutates": False,
                            "trust_required": False,
                        },
                        "forge.assets.add": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                        },
                        "forge.assets.delete": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                            "confirmation_required": True,
                        },
                        "forge.assets.edit": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                        },
                        "forge.assets.refresh": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                            "async_background": False,
                        },
                        "forge.assets.cancelPending": {
                            "supported": True,
                            "mutates": False,
                            "trust_required": False,
                        },
                        "forge.assets.checkPlan": {
                            "supported": True,
                            "mutates": False,
                            "trust_required": False,
                        },
                        "forge.assets.pruneLegacy": {
                            "supported": True,
                            "mutates": True,
                            "trust_required": True,
                            "confirmation_required": True,
                        },
                    },
                },
                "execute_preview": {
                    "supported": True,
                    "method": "forge.executePreview",
                    "dry_run_method": "forge.execute",
                    "mutates": False,
                    "runs_tools": False,
                    "runs_shell_commands": False,
                    "starts_workers": False,
                },
                "execute": {
                    "supported": True,
                    "supported_modes": ["review"],
                    "selected_task_ids_required": True,
                    "job_based": True,
                    "approval_gated": True,
                    "workspace_trust_required": True,
                    "sandbox_required": True,
                    "dry_run_supported": True,
                    "preview_method": "forge.executePreview",
                    "behavior": "review_mode_only",
                    "max_steps_param": True,
                    "no_log_param": True,
                    "subagents_supported": False,
                    "job_status_model": "data_outcome_completed_with_result",
                    "subagents_policy": "disabled_for_ide_forge_execute_v1",
                    "subagents_rationale": (
                        "IDE Forge Execute keeps subagents disabled until worker lifecycle, "
                        "sandbox, approval, and cancellation semantics are strong enough."
                    ),
                    "auto_mode": "unsupported_fail_closed",
                    "unsafe_modes": {
                        "supported": False,
                        "blocked_until_security_model": ["auto", "fullaccess"],
                        "experimental_flags": {
                            "auto": False,
                            "fullaccess": False,
                            "forge.swarm": False,
                        },
                        "enable_by_default": False,
                        "required_before_reassessment": [
                            "real_active_runtime_cancellation",
                            "worker_lifecycle_ownership",
                            "sandbox_guarantees",
                            "approval_ux_for_broad_mutation",
                        ],
                        "reason": (
                            "Auto/fullaccess execution remains blocked because IDE v1 lacks "
                            "strong enough cancellation, worker lifecycle, sandbox, and approval "
                            "guarantees for broad mutation."
                        ),
                    },
                    "cancellation": "cooperative_checkpoint_cancellation",
                    "active_cancellation_supported": True,
                },
                "cancel": {
                    "supported": True,
                    "callable": True,
                    "behavior": "cooperative_checkpoint_cancellation",
                    "covered_job_kinds": [
                        "forge_plan",
                        "forge_plan_regenerate",
                        "forge_review",
                        "forge_execute",
                        "forge_swarm",
                    ],
                    "lifecycle_states": [
                        "queued",
                        "running",
                        "cancellation_requested",
                        "cancelled",
                        "completed",
                        "failed",
                    ],
                    "unsupported_lifecycle_states": [],
                    "interrupt_kind": "cooperative",
                    "checks_between_steps": True,
                    "hard_interrupt": False,
                    "must_not_mark_cancelled_without_interrupt": False,
                },
                "swarm": {
                    "supported": True,
                    "async": True,
                    "job_based": True,
                    "start_method": "forge.swarm.start",
                    "status_method": "forge.swarm.status",
                    "result_method": "forge.swarm.result",
                    "cancel_method": "forge.swarm.cancel",
                    "reconcile_method": "forge.swarm.reconcile",
                    "workspace_trust_required": True,
                    "parallel_max": 8,
                    "cancellation": "cooperative_checkpoint_cancellation",
                    "interrupted_task_status": "interrupted",
                    "interrupted_worktrees_preserved": True,
                    "disjoint_write_scopes": "guaranteed_by_scheduler_invariant",
                    "write_scope_guard": "swarm_layer_tool_dispatch_guard",
                    "approvals": {
                        "yes_auto_approval": False,
                        "routing": "host_managed_per_session_with_task_attribution",
                        "timeout_behavior": "task_stays_paused_never_auto_denied",
                        "siblings_continue_while_paused": True,
                        "pending_event_state": "approval_pending",
                    },
                    "approval_scope_grants": {
                        "supported": True,
                        "shape": "array_of_kind_scope_objects",
                        "semantics": "recorded_as_allow_for_session_scopes_at_launch",
                        "max_entries": 32,
                    },
                    "task_event_states": [
                        "scheduled",
                        "started",
                        "progress",
                        "approval_pending",
                        "interrupted",
                        "failed",
                        "merged",
                    ],
                    "task_event_type": "swarm_worker_state_changed",
                    "reconcile": {
                        "read_only_report": True,
                        "actions": ["report", "harvest", "discard"],
                        "harvest_trust_required": True,
                        "discard_trust_required": True,
                        "discard_confirmation_required": True,
                        "idempotent": True,
                    },
                    "merge_behavior": "review_only_per_task_apply_discard",
                    "review": {
                        "list_method": "forge.swarm.review",
                        "apply_method": "forge.swarm.apply",
                        "discard_method": "forge.swarm.discard",
                        "working_tree_touched_only_on_apply": True,
                        "never_commits": True,
                        "untracked_files_surfaced": True,
                        "apply_trust_required": True,
                        "discard_trust_required": True,
                        "discard_confirmation_required": True,
                        "failure_recovery_offer": "regenerate_subtree_via_forge.plan.regenerate.start",
                    },
                },
            },
            "diffs": {
                "supported": True,
                "opaque_ids": True,
                "arbitrary_file_reads": False,
                "default_max_bytes": 65536,
                "max_bytes": 1048576,
                "redaction": "protocol_preview",
            },
            "cancellation": {
                "idle_sessions": True,
                "active_jobs": True,
                "close_when_idle": True,
                "close_when_idle_cancels_queued_prompts": True,
                "close_when_idle_releases_owned_resources": True,
                "behavior": "cooperative_checkpoint_cancellation",
                "lifecycle_states": [
                    "queued",
                    "running",
                    "cancellation_requested",
                    "cancelled",
                    "completed",
                    "failed",
                ],
                "unsupported_lifecycle_states": [],
                "interrupt_kind": "cooperative",
                "checks_between_steps": True,
                "hard_interrupt": False,
                "stale_active_jobs_reconciled": True,
            },
            "management": MANAGEMENT_FEATURES,
            "approvals": {
                "round_trip": True,
                "default_deny": True,
                "session_scoped_allow": True,
                "supported_kinds_for_session_allow": [
                    "shell_run",
                    "shell_background",
                    "custom_tool_run",
                    "mcp_tool_run",
                    "fs_write",
                    "fs_edit",
                    "fs_move",
                    "fs_copy",
                    "fs_delete",
                    "fs_mkdir",
                    "git_apply_patch",
                    "verify_run",
                ],
                "timeout_seconds_default": DEFAULT_APPROVAL_TIMEOUT_SECONDS,
            },
            "event_replay": {
                "bounded": True,
                "default_retained_events": 1000,
                "max_response_events": 500,
                "preserved_across_trace_clear": True,
            },
        },
    }


def health_payload() -> dict[str, Any]:
    return {
        "ok": True,
        "name": "alysis-ide-bridge",
        "alysis_version": __version__,
        "protocol_version": PROTOCOL_VERSION,
        "capabilities": capabilities_payload(),
    }
